pool: windows

variables:
  DEPLOYMENT_NAME: 'my-deployment'
  REPLICA_COUNT: '3'
  APP_NAME: 'my-app'
  CONTAINER_NAME: 'my-container'
  IMAGE_NAME: 'my-registry/my-image:latest'
  CONTAINER_PORT: '8080'
  
- task: KubernetesManifest@1
  displayName: Bake K8s manifests
  name: bake
  inputs:
    action: 'bake'
    renderType: 'kustomize'
    kustomizationPath: '$(System.DefaultWorkingDirectory)'
- task: KubernetesManifest@1
    displayName: 'Deploy using Kustomize'
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'YourKubernetesConnection'  
      kustomizePath: 'path/to/kustomization'  
      kustomizationType: 'kustomization.yaml'  
      namespace: 'your-namespace'  
